### ISSUE TITLE
quit the app

### ISSUE THREAD

**Issue by PatrickMuringer** [maximbilan/Mac-OS-X-App-Menu-Bar-Popup#1]
how would you quit the app (it stays on when clicking outside)?

**Comment by maximbilan** [comment]
Hi,

You can easily add the quit button into your application. I've updated the example, please pull from github.

**Comment by PatrickMuringer** [comment]
hi

very kind of you. thanks a lot.

**Comment by maximbilan** [comment]
No problem. Thanks for using my repo.

**Comment by PatrickMuringer** [comment]
hi,any idea how to have a custom background on the overall window (including the triangle)?On 20 Aug 2016, at 08:17, Maxim Bilan notifications@github.com wrote:Hi,You can easily add the quit button into your application. I've updated the example, please pull from github.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/maximbilan/Mac-OS-X-App-Menu-Bar-Popup","title":"maximbilan/Mac-OS-X-App-Menu-Bar-Popup","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/maximbilan/Mac-OS-X-App-Menu-Bar-Popup" class="">https://github.com/maximbilan/Mac-OS-X-App-Menu-Bar-Popup</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maximbilan in #1: Hi,\r\n\r\nYou can easily add the quit button into your application. I've updated the example, please pull from github."}],"action":{"name":"View Issue","url":"<a href="https://github.com/maximbilan/Mac-OS-X-App-Menu-Bar-Popup/issues/1#issuecomment-241182383" class="">https://github.com/maximbilan/Mac-OS-X-App-Menu-Bar-Popup/issues/1#issuecomment-241182383</a>"}}}
