### ISSUE TITLE
integrate wkwebview

### ISSUE THREAD

**Issue by copypasteho** [maximbilan/Mac-OS-X-App-Menu-Bar-Popup#3]
Love this! With a few tweaks this compiles perfectly under High Sierra, with the latest XCode. As far as customizations are concerned: how would one go about integrating a WKWebView into the window if the end goal is to embed HTML and JS content?

**Comment by maximbilan** [comment]
Thanks. You can add anything you want to ViewController, the WebView including.

**Comment by copypasteho** [comment]
Thanks for the response. The webview integration worked, but sadly overrides and hides the popover even if I resize it. I'm having a crazy time trying to wrap my head around integrating WKWebViews to play nice with existing views.
